steps:
  # install dependencies with dev
  - name: 'vinelab/nginx-php:composer'
    args: ['-c', '/usr/local/bin/composer install --no-interaction']
    entrypoint: '/bin/bash'
    env:
      - 'COMPOSER_AUTH=$_COMPOSER_AUTH'
  # open storage directories for writing
  - name: 'debian'
    entrypoint: 'bash'
    args: ['-c', 'chmod -R o+w ./storage ./bootstrap/cache']
  # build code image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BUILD_ID.$COMMIT_SHA', '.']
  # push code image
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$BUILD_ID.$COMMIT_SHA"]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_CLOUDSDK_COMPUTE_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLOUDSDK_CONTAINER_CLUSTER'
  # re-deploy pod
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/criteria-service', 'criteria-service=gcr.io/$PROJECT_ID/$REPO_NAME:$BUILD_ID.$COMMIT_SHA']
