steps:
  # install dependencies with dev
  - name: 'vinelab/nginx-php:composer'
    args:
      - '-v $(pwd):/code'
      - '--workdir /code'
      - '/bin/bash -c "composer self-update && composer install --no-interaction"'
    env:
      - 'COMPOSER_AUTH=$_COMPOSER_AUTH'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME']
  - images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME']
