FROM vinelab/nginx-php

MAINTAINER Abed Halawi <abed.halawi@vinelab.com>

RUN apt-get update && apt-get install -y git

COPY . /code

WORKDIR /code

ADD run_tests.sh /code/run_tests.sh

CMD ["bash", "run_tests.sh"]
