#!/bin/bash

pwd

ls

apt-get install curl php5-cli git

curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer${WORKSPACE}

echo "=> Installing dependencies"
composer install --prefer-dist --no-interaction --no-dev

echo "=> opening storage directories"
chmod -R o+w ./storage
chmod -R o+w ./bootstrap/cache
