#!/bin/bash

docker run --rm \
    -v $(pwd):/code \
    --workdir /code \
    -e COMPOSER_AUTH=$COMPOSER_AUTH \
    vinelab/nginx-php:composer \
    /bin/bash -c "composer self-update && composer install --no-dev --no-interaction"
