#!/bin/bash

pwd

ls

echo "=> Installing composer"
apt-get install -y curl php5-cli git
curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
composer

echo "=> Installing dependencies"
composer install --prefer-dist --no-interaction --no-dev

echo "=> opening storage directories"
chmod -R o+w ./storage
chmod -R o+w ./bootstrap/cache
